name: InventoryRestore
version: ${project.version}
main: com.github.evancolewright.inventoryrestore.IRPlugin
authors: [ evancolewright ]
description: A simple and effective inventory-restoring plugin for all versions of Minecraft.
commands:
  inventoryrestore:
    permission: inventoryrestore.restore
    aliases:
      - ir
      - invrestore
